# Generated by Django 6.0.5 on 2026-06-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_qrmenu_alter_menuitems_menu_delete_qrmneu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
    ]
