# Generated by Django 6.0.5 on 2026-06-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_alter_menuitem_options_menuitem_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='avaivlable',
            new_name='available',
        ),
    ]
