# Generated by Django 6.0.5 on 2026-06-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_avaivlable_menuitem_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
