# Generated by Django 6.0.5 on 2026-05-30 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 30, 15, 13, 2, 944688, tzinfo=datetime.timezone.utc)),
        ),
    ]
