# Generated by Django 6.0.5 on 2026-05-30 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_code',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 30, 15, 14, 52, 247935, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
