# Generated by Django 6.0.5 on 2026-05-30 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otp_code_created_at_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_code',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
